### ISSUE TITLE
how to run this project

### ISSUE THREAD

**Issue by zs0129** [igorpejic/visapi#2]
Hi, I'm working on bin packing, too, with the classic BR instances and heuristic tree search methods. Could you please tell me how to run this project? I hope to compare it with my algorithm. Thanks for your kindness!

**Comment by igorpejic** [comment]
Hi @zs0129 the work is still WIP.

Instructions on how to run it will follow soon.

Sorry

**Comment by igorpejic** [comment]
Added instructions.
